### ISSUE TITLE
Whitespace comparison in functions

### ISSUE THREAD

**Issue by dkent** [djrobstep/migra#188] opened 2021-08-04 16:18 UTC
Minor issue. When comparing functions, it appears that if the tabs/whitespace aren't identical, the functions are treated as different. I changed my editor to use "smart tabs" (aka 4 spaces) and the issue was resolved. It would be nice if the comparison of function bodies would ignore these types of whitespace differences.

**Comment by maximsmol** [comment] 2022-04-13 20:00
Duplicate of #34

**Closed by maximsmol** 2022-04-13 20:00 UTC
Labels: duplicate, enhancement
