### ISSUE TITLE
Error with character encoding

### ISSUE THREAD

**Issue by PedroSolintel** [djrobstep/migra#13] opened 2017-11-28 14:10 UTC
I was receiving the following error:

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\migra.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\migra\command.py", line 72, in do_command
    status = run(args)
  File "c:\python27\lib\site-packages\migra\command.py", line 59, in run
    print(m.sql, file=out)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 10804: ordinal not in range(128)
```
I've searched for a solution and found this one: https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console

Then I modified your `command.py` using [mike rodent's](https://stackoverflow.com/a/35903736/6882194) code:

```
def run(args, out=None, err=None):
    if not out:
        out = sys.stdout  # pragma: no cover

    if not err:
        err = sys.stderr  # pragma: no cover

    with \
            arg_context(args.dburl_from) as ac0, \
            arg_context(args.dburl_target) as ac1:
        m = Migration(ac0, ac1)

        if args.unsafe:
            m.set_safety(False)
        m.add_all_changes()

        try:
            if m.statements:
                 pr(m.sql, out)
        except UnsafeMigrationException:
            print('-- ERROR: destructive statements generated. Use the --unsafe flag to suppress this error.', file=err)
            return 3

        if not m.statements:
            return 0
        else:
            return 2


def do_command():  # pragma: no cover
    args = parse_args(sys.argv[1:])
    status = run(args)
    sys.exit(status)
	

def pr(s, out):
    try:
        print(s, file=out)
    except UnicodeEncodeError:
        for c in s:
            try:
                print( c, end='', file=out)
            except UnicodeEncodeError:
                print( '?', end='', file=out)
```

Maybe you can find a better looking solution. Anyway, it's working wonderfully now! You've done a very good job!

**Comment by djrobstep** [comment] 2017-11-30 06:24
Thank you, I'm glad it's working well for you!

While this does make it work in your case, I think it would be dangerous to change the code to silently print out question marks instead of the correct characters.

I've had a similar issue reported before relating to unicode errors with the windows console, and back then I responded:

> The more correct approach here is to change the stdout encoding to support utf-8. There are ways to configure this: https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8
>
> And it seems this is now fixed in python 3.6 at least: https://docs.python.org/3/whatsnew/3.6.html#pep-528-change-windows-console-encoding-to-utf-8
>
> There's probably code we can add to work around this, but the best solution might be to add some windows-specific documentation about this and encourage users to upgrade their python version? What do you think?

**Comment by PedroSolintel** [comment] 2017-11-30 13:12
Updated to Python 3.6 and followed the instructions on the solutions you mentioned but it still doesn't work.

**Comment by djrobstep** [comment] 2018-01-12 03:16
What is the value of `sys.stdout.encoding` you get from python 3.6?

**Comment by PedroSolintel** [comment] 2018-01-12 10:10
`sys.stdout.encoding` returns me `'utf-8'`.

**Comment by mdouchin** [comment] 2018-01-12 12:52
Hi, I tested it with a database (french) which may contain non-ascii chars in table or column comments, and I also got a encoding issue, see

```
Traceback (most recent call last):
  File "/usr/local/bin/migra", line 11, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python2.7/dist-packages/migra/command.py", line 73, in do_command
    status = run(args)
  File "/usr/local/lib/python2.7/dist-packages/migra/command.py", line 52, in run
    m = Migration(ac0, ac1)
  File "/usr/local/lib/python2.7/dist-packages/migra/migra.py", line 20, in __init__
    self.changes.i_from = get_inspector(x_from)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/get.py", line 19, in get_inspector
    return ic(c)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 331, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 334, in load_all
    self.load_all_relations()
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 481, in load_all_relations
    self.sequences = od((i.quoted_full_name, i) for i in sequencelist)
  File "/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 481, in <genexpr>
    self.sequences = od((i.quoted_full_name, i) for i in sequencelist)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/inspected.py", line 9, in quoted_full_name
    quoted_identifier(self.schema), quoted_identifier(self.name))
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/misc.py", line 38, in quoted_identifier
    s = '"{}"'.format(identifier.replace('"', '""'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 10: ordinal not in range(128)

```

**Comment by djrobstep** [comment] 2018-02-16 07:33
@mdouchin and @PedroSolintel, I've confirmed migra works correctly with these characters using python 3.6. If you have any further trouble, I suggest upgrading to 3.6, which contains fixes for unicode console output. 

I'll add some notes to the readme documentation for windows users, addressing these problems, but since it can be fixed by upgrading, I'll close this issue for now. Thanks again for reporting your experiences and helping make migra better!

**Closed by djrobstep** 2018-02-16 07:33 UTC
Labels: bug
