### ISSUE TITLE
Tables With Primary Keys Cause Error

### ISSUE THREAD

**Issue by bitner** [djrobstep/migra#173] opened 2021-03-16 14:07 UTC
Running migra between an empty database (tried both PG12 and PG13) and a database with a single table with a primary returns an error.

Table:
CREATE TABLE IF NOT EXISTS test(
    id int primary key,
    foo text
);

Error when running "migra --schema pgstac --unsafe $EMPTYDBURL $TODBURL >migration.sql"

Traceback (most recent call last):
  File "/usr/local/bin/migra", line 10, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python3.7/dist-packages/migra/command.py", line 108, in do_command
    status = run(args)
  File "/usr/local/lib/python3.7/dist-packages/migra/command.py", line 79, in run
    m = Migration(ac0, ac1, schema=schema, exclude_schema=exclude_schema)
  File "/usr/local/lib/python3.7/dist-packages/migra/migra.py", line 34, in __init__
    x_target, schema=schema, exclude_schema=exclude_schema
  File "/usr/local/lib/python3.7/dist-packages/schemainspect/get.py", line 20, in get_inspector
    inspected = ic(c)
  File "/usr/local/lib/python3.7/dist-packages/schemainspect/pg/obj.py", line 1073, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/local/lib/python3.7/dist-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/local/lib/python3.7/dist-packages/schemainspect/pg/obj.py", line 1077, in load_all
    self.load_all_relations()
  File "/usr/local/lib/python3.7/dist-packages/schemainspect/pg/obj.py", line 1440, in load_all_relations
    index_name = quoted_identifier(i.index, schema=i.schema)
  File "/usr/local/lib/python3.7/dist-packages/schemainspect/misc.py", line 35, in quoted_identifier
    s = '"{}"'.format(identifier.replace('"', '""'))
AttributeError: 'function' object has no attribute 'replace'

**Comment by pietrobaricco** [comment] 2021-03-16 16:46
I get a similar error when running a migration using pg13 (on Fedora 33), while pg10 on CentOS 7 works fine.
I am comparing two non empty databases.

`Traceback (most recent call last):
  File "/usr/local/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python3.9/site-packages/migra/command.py", line 108, in do_command
    status = run(args)
  File "/usr/local/lib/python3.9/site-packages/migra/command.py", line 79, in run
    m = Migration(ac0, ac1, schema=schema, exclude_schema=exclude_schema)
  File "/usr/local/lib/python3.9/site-packages/migra/migra.py", line 25, in __init__
    self.changes.i_from = get_inspector(
  File "/usr/local/lib/python3.9/site-packages/schemainspect/get.py", line 20, in get_inspector
    inspected = ic(c)
  File "/usr/local/lib/python3.9/site-packages/schemainspect/pg/obj.py", line 1073, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/local/lib/python3.9/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/local/lib/python3.9/site-packages/schemainspect/pg/obj.py", line 1077, in load_all
    self.load_all_relations()
  File "/usr/local/lib/python3.9/site-packages/schemainspect/pg/obj.py", line 1440, in load_all_relations
    index_name = quoted_identifier(i.index, schema=i.schema)
  File "/usr/local/lib/python3.9/site-packages/schemainspect/misc.py", line 35, in quoted_identifier
    s = '"{}"'.format(identifier.replace('"', '""'))
AttributeError: 'function' object has no attribute 'replace'`

**Comment by djrobstep** [comment] 2021-03-16 23:03
This looks to be an issue caused by the latest release of `sqlalchemy`. I'm looking into it, but in the short term you can downgrade to `sqlalchemy<1.4` to avoid the problem.

**Comment by djrobstep** [comment] 2021-03-17 08:14
This is now fixed!

**Closed by djrobstep** 2021-03-17 08:14 UTC
