### ISSUE TITLE
Droping and recreating indexes

### ISSUE THREAD

**Issue by jribenfors** [djrobstep/migra#74] opened 2019-02-08 16:24 UTC
I'm comparing a source 9.5.10 database with a target at 9.5.13

Migra is suggesting I drop and recreate most of the indexes.  The indexes are identical - I ran one of the drop/recreate suggestions, then ran migra again and it made the same suggestion.

```
drop index if exists "public"."alarm_status_datetime_idx";
CREATE INDEX alarm_status_datetime_idx ON public.alarm_status USING btree (datetime);
```
And the index:
```
CREATE INDEX alarm_status_datetime_idx ON public.alarm_status 
USING btree (datetime) TABLESPACE pg_default;
```

**Comment by jribenfors** [comment] 2019-02-08 17:07
Ah, you support 10 and above.

**Comment by djrobstep** [comment] 2019-02-11 10:07
I can't reproduce this sorry... Can you provide more information?

**Comment by djrobstep** [comment] 2019-03-10 10:08
Closing this for now, please file a new report if you have any further problems.

**Closed by djrobstep** 2019-03-10 10:08 UTC

**Comment by akeeman** [comment] 2019-03-20 09:02
I guess this is a duplicate of #61
