### ISSUE TITLE
Recreating the indexes

### ISSUE THREAD

**Issue by hoducha** [djrobstep/migra#61] opened 2018-11-29 10:11 UTC
When I run the migra with --unsafe option, it always generate a file that includes the SQL for recreating the indexes like this:
```sql
drop index if exists "public"."users_id_pk";

CREATE UNIQUE INDEX users_id_pk ON users USING btree (id);
```
Any ideas?

**Comment by djrobstep** [comment] 2018-11-30 16:38
Can't reproduce this, do you have a minimal example of two databases where this occurs?

**Comment by djrobstep** [comment] 2018-12-01 23:32
Closing this for now, feel free to reopen if the problem continues

**Closed by djrobstep** 2018-12-01 23:32 UTC

**Comment by akeeman** [comment] 2019-03-20 09:01
Same problem here...

**Comment by djrobstep** [comment] 2019-03-20 09:21
I can't do anything without a reproducible test case, can you provide one?
