### ISSUE TITLE
DEFERRABLE status on constraints isn't properly tracked

### ISSUE THREAD

**Issue by dancrumb** [djrobstep/migra#165] opened 2021-01-12 18:34 UTC
I have two databases that I am trying to bring into sync, in terms of structure.

When I run

```
migra --unsafe --schema public <staging_URL> <goal_URL>
```

I get

```
alter table "public"."practices" drop constraint "wim_unique_id";

alter table "public"."providerDetails" drop constraint "wim_unique_id_providerDetails";

drop index if exists "public"."wim_unique_id";

drop index if exists "public"."wim_unique_id_providerDetails";

CREATE UNIQUE INDEX wim_unique_id ON public.practices USING btree ("wimId");

CREATE UNIQUE INDEX "wim_unique_id_providerDetails" ON public."providerDetails" USING btree ("wimId");

alter table "public"."practices" add constraint "wim_unique_id" UNIQUE using index "wim_unique_id";

alter table "public"."providerDetails" add constraint "wim_unique_id_providerDetails" UNIQUE using index "wim_unique_id_providerDetails";
```

I run that SQL against my staging DB.

Here's the output

```
ALTER TABLE
NOTICE:  index "wim_unique_id" does not exist, skipping
ALTER TABLE
NOTICE:  index "wim_unique_id_providerDetails" does not exist, skipping
DROP INDEX
DROP INDEX
CREATE INDEX
CREATE INDEX
ALTER TABLE
ALTER TABLE
```

Then I run

```
migra --unsafe --schema public <staging_URL> <goal_URL>
```

I get the same migration SQL and so it repeats.

Any idea why?

**Comment by djrobstep** [comment] 2021-01-12 21:30
Are you sure you're running the generated script against the correct database? It's otherwise hard to see how you could be seeing the same output after as before.

If it persists, try to create a minimal reproducible example and I can have a look.

**Comment by dancrumb** [comment] 2021-01-12 21:37
Just to make sure I'm not being a dope.

Given 2 databases, CURRENT and FUTURE.

CURRENT is my current db with its schema
FUTURE is a reference db containing what the schema I want

If I run

```
migra ---unsafe --schema public CURRENT FUTURE > migration.sql
```

I'll get a list of SQL commands.

I then run

```
psql CURRENT -f migration.sql
```

Then CURRENT and FUTURE should have the same schema, right?

**Comment by dancrumb** [comment] 2021-01-12 21:47
As a point of reference, I ran the following:


```
➜  ohana git:(main) migra --unsafe --schema public $(node ./tools/createSqlUrl.js staging) $(node ./tools/createSqlUrl.js test)
alter table "public"."practices" drop constraint "wim_unique_id";

alter table "public"."providerDetails" drop constraint "wim_unique_id_providerDetails";

drop index if exists "public"."wim_unique_id";

drop index if exists "public"."wim_unique_id_providerDetails";

CREATE UNIQUE INDEX wim_unique_id ON public.practices USING btree ("wimId");

CREATE UNIQUE INDEX "wim_unique_id_providerDetails" ON public."providerDetails" USING btree ("wimId");

alter table "public"."practices" add constraint "wim_unique_id" UNIQUE using index "wim_unique_id";

alter table "public"."providerDetails" add constraint "wim_unique_id_providerDetails" UNIQUE using index "wim_unique_id_providerDetails";
```

Then, I manually removed the Unique constraint on the `public.practices.wimId` field.

```
➜  ohana git:(main) migra --unsafe --schema public $(node ./tools/createSqlUrl.js staging) $(node ./tools/createSqlUrl.js test)
alter table "public"."providerDetails" drop constraint "wim_unique_id_providerDetails";

drop index if exists "public"."wim_unique_id_providerDetails";

CREATE UNIQUE INDEX wim_unique_id ON public.practices USING btree ("wimId");

CREATE UNIQUE INDEX "wim_unique_id_providerDetails" ON public."providerDetails" USING btree ("wimId");

alter table "public"."practices" add constraint "wim_unique_id" UNIQUE using index "wim_unique_id";

alter table "public"."providerDetails" add constraint "wim_unique_id_providerDetails" UNIQUE using index "wim_unique_id_providerDetails";
```

Then, I manually removed the Unique constraint on the `public.providerDetails.wimId` field.

```
➜  ohana git:(main) migra --unsafe --schema public $(node ./tools/createSqlUrl.js staging) $(node ./tools/createSqlUrl.js test)
CREATE UNIQUE INDEX wim_unique_id ON public.practices USING btree ("wimId");

CREATE UNIQUE INDEX "wim_unique_id_providerDetails" ON public."providerDetails" USING btree ("wimId");

alter table "public"."practices" add constraint "wim_unique_id" UNIQUE using index "wim_unique_id";

alter table "public"."providerDetails" add constraint "wim_unique_id_providerDetails" UNIQUE using index "wim_unique_id_providerDetails";
```

Then, I manually ran those 4 queries.

```
migra --unsafe --schema public $(node ./tools/createSqlUrl.js staging) $(node ./tools/createSqlUrl.js test)
alter table "public"."practices" drop constraint "wim_unique_id";

alter table "public"."providerDetails" drop constraint "wim_unique_id_providerDetails";

drop index if exists "public"."wim_unique_id";

drop index if exists "public"."wim_unique_id_providerDetails";

CREATE UNIQUE INDEX wim_unique_id ON public.practices USING btree ("wimId");

CREATE UNIQUE INDEX "wim_unique_id_providerDetails" ON public."providerDetails" USING btree ("wimId");

alter table "public"."practices" add constraint "wim_unique_id" UNIQUE using index "wim_unique_id";

alter table "public"."providerDetails" add constraint "wim_unique_id_providerDetails" UNIQUE using index "wim_unique_id_providerDetails";
```

**Comment by dancrumb** [comment] 2021-01-12 21:48
The relevant table schemas are:

```
--
-- Professional Identities
--
CREATE TABLE "providerDetails" (
    id int generated by default as identity primary key,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "firstName" character varying(255),
    "lastName" character varying(255),
    "practiceName" character varying(255),
    "practicePhone" character varying(50),
    searchable boolean DEFAULT FALSE,
    "practiceId" integer,
    "providerId" integer,
    speciality character varying(255) DEFAULT ''::character varying NOT NULL,
    qualification character varying(64) DEFAULT ''::character varying NOT NULL,
    "practiceFax" character varying(50) DEFAULT ''::character varying,
    "updaterId" integer,
    "wimId" character varying(255),
    email character varying(255),
    phone text
);

ALTER TABLE ONLY "providerDetails"
    ADD CONSTRAINT "providerDetails_email_key" UNIQUE (email);

ALTER TABLE ONLY "providerDetails"
    ADD CONSTRAINT "wim_unique_id_providerDetails" UNIQUE ("wimId") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "providerDetails_providerId_index" ON "providerDetails" USING btree ("providerId");
```

```
--
-- Practices
--
CREATE TABLE practices (
    id int generated by default as identity primary key,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    name character varying(255),
    address character varying(255) NOT NULL,
    phone character varying(50) NOT NULL,
    url character varying(255),
    "timeZone" character varying(255) DEFAULT 'Etc/UTC' ::character varying NOT NULL,
    fax character varying(50) DEFAULT ''::character varying,
    "wimId" character varying(255)
);


ALTER TABLE ONLY practices
    ADD CONSTRAINT "wim_unique_id" UNIQUE ("wimId") DEFERRABLE INITIALLY DEFERRED;
```

**Comment by dancrumb** [comment] 2021-01-12 21:49
On a hunch, I removed the `DEFERRABLE INITIALLY DEFERRED` clauses and, whaddaya know? everything worked.

Soooo... from my perspective, I'm good, but hopefully, that's enough to narrow down what was going on.

**Comment by djrobstep** [comment] 2021-01-12 22:37
Thanks for investigating, it looks like the deferrable tracking code on constraints isn't complete, I'll fix this up soon so those changes are handled.

**Comment by djrobstep** [comment] 2021-01-13 02:51
I've pushed out a quick fix for this, which should solve the problem you were encountering earlier. Any further problems, please let me know.

**Closed by djrobstep** 2021-01-13 02:51 UTC
