### ISSUE TITLE
KeyError: '"request"."cid"'

### ISSUE THREAD

**Issue by testarossaaaaa** [djrobstep/migra#107] opened 2019-12-12 11:17 UTC
```
Traceback (most recent call last):
  File "/usr/bin/migra", line 10, in <module>
    sys.exit(do_command())
  File "/usr/lib/python3.6/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/usr/lib/python3.6/site-packages/migra/command.py", line 72, in run
    m = Migration(ac0, ac1, schema=schema)
  File "/usr/lib/python3.6/site-packages/migra/migra.py", line 22, in __init__
    self.changes.i_from = get_inspector(x_from, schema=schema)
  File "/usr/lib/python3.6/site-packages/schemainspect/get.py", line 18, in get_inspector
    inspected = ic(c)
  File "/usr/lib/python3.6/site-packages/schemainspect/pg/obj.py", line 718, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/lib/python3.6/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/lib/python3.6/site-packages/schemainspect/pg/obj.py", line 727, in load_all
    self.load_deps()
  File "/usr/lib/python3.6/site-packages/schemainspect/pg/obj.py", line 799, in load_deps
    self.selectables[x_dependent_on].dependents.append(x)
KeyError: '"request"."cid"'
```

request.cid is a simple working sql function, nothing special.

**Comment by djrobstep** [comment] 2019-12-12 18:00
What version of migra/schemainspect are you running? Try upgrading both. Failing that, can you give me a minimal schema that reproduces the problem?

**Comment by djrobstep** [comment] 2019-12-17 23:00
Closing for now, please feel free to reopen if the problem is still occurring.

**Closed by djrobstep** 2019-12-17 23:00 UTC
